### ISSUE TITLE
遇到一些问题

### ISSUE THREAD

**Issue by dowhilenet** [MofeLee/how-to-fxxk-gfw#1]
你好，很高兴能看到这么详细的一个教程，但是我在实践的过程中遇到了一些问题。

执行 `proxychains4 curl google.com` 

错误提示 `curl: (7) Failed to connect to google.com port 80: Operation timed out` 

很明显是没有翻墙成功，现在我使用 ShadowsocksX 在浏览器中已经可以翻墙了。但是在命令行中还是不行，不知到是不是我哪里 的姿势不争取

**Comment by mofelee** [comment]
1. 什么操作系统？系统版本号多少？
2. 用 `telnet localhost 1080` 是否能正常连接？
3. `proxychains4` 的配置文件修改了吗？注意配置文件在不同系统安装的位置可能不一样。
4. 是否有设置`http_proxy`和`https_proxy`环境变量？

**Comment by dowhilenet** [comment]
mac 10.11.6
`proxychains4 curl baidu.com` 都是可以的

`telnet localhost 1080` 好像不可以

都使用 brew 来安装的

**Comment by dowhilenet** [comment]
```
pc curl baidu.com
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
<html>
<meta http-equiv="refresh" content="0;url=http://www.baidu.com/">
</html>
```

**Comment by dowhilenet** [comment]
把   `/usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf` 文件修改成和你一样

**Comment by mofelee** [comment]
你可以试试`pc curl ifconfig.co`
看看显示的是不是你代理服务器的ip地址

你用的是什么shadowsocks客户端连接服务器？很有可能是你的shadowsocks客户端没有成功连接到服务器，

如果确认能成功连接到服务器，那可能你有手动修改过shadowsocks在本地暴露出来的端口号，检查下端口号是否为1080，如果不是，把`proxychains.conf`配置文件中的1080改为你自定义的端口号

**Comment by dowhilenet** [comment]
我使用的是 shadowsocksX

`pc curl ifconfig.co`
结果是 `118.74.133.187`

我 `ping` 出来的代理服务器IP `103.192.224.29`

看来并不一致。
通过  [ shadowsocksX](https://github.com/shadowsocks/shadowsocks-iOS/wiki/Shadowsocks-for-OSX-%E5%B8%AE%E5%8A%A9) 在浏览器中是可以翻墙成功的。

**Comment by mofelee** [comment]
可能是暴露出来的端口有问题

![image](https://cloud.githubusercontent.com/assets/5069410/16549802/80be4202-41d5-11e6-8202-362f2249faca.png)
1. turn on shadowsocks
2. 打开网络配置，下载自动代理服务的配置文件
3. 端口号在下图的位置

![image](https://cloud.githubusercontent.com/assets/5069410/16549833/c1025bd2-41d5-11e6-9739-33d8eedcaeec.png)

**Comment by dowhilenet** [comment]
```
var proxy = "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;";
```

端口 确实是 1080 ， 按照您给的方法

**Comment by dowhilenet** [comment]
我的配置文件中 `/usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf`

```
# meanwile
# defaults set to "tor"
socks5 127.0.0.1 1080
```

**Comment by mofelee** [comment]
`telnet 127.0.0.1 1080`连接不上么？那就奇怪了。。。

**Comment by mofelee** [comment]
你先打开shadowsocks, 再在网页打开 http://ifconfig.co 这个网站，看看显示的是服务器的ip还是自己的ip

**Comment by dowhilenet** [comment]
登陆  http://ifconfig.co  显示的IP  是 自己的 IP  ［118.74.133.187］

服务商提供的服务器 [hk02-76.ssv7.net] 的 IP ［103.192.224.29］

telnet 127.0.0.1 1080  停在那里不动

**Comment by mofelee** [comment]
shadowsocks打开全局模式
然后用safari打开 http://ifconfig.co

**Comment by dowhilenet** [comment]
嗯嗯，全局模式下IP 是服务商提供的IP了

**Comment by mofelee** [comment]
你试过这里的解决方法吗？
![image](https://cloud.githubusercontent.com/assets/5069410/16572273/8140e15c-4299-11e6-9b46-47d3f94d1e3a.png)

**Comment by dowhilenet** [comment]
我通过 brew 下载之后默认的路径是 `/usr/local/Cellar/proxychains-ng/4.11`

是不是要把他 拷贝到 `~/bin` 下？

**Comment by mofelee** [comment]
只需要拷贝bin里的文件
![image](https://cloud.githubusercontent.com/assets/5069410/16572878/1e03a24e-42a0-11e6-9744-13e2efd1f381.png)

**Comment by dowhilenet** [comment]
OK，我已经把拷贝到了 ~/bin  

并且 在  `.zshrc`文件中添加了

```
export PATH="/Users/xiaolei/bin:$PATH"
alias pc='proxychains4'
```

重启命令行之后，执行  

`pc curl google.com` 之后还是显示  

Failed to connect to google.com port 80: Operation timed out

浏览器中 访问Google是没有问题的

**Comment by mofelee** [comment]
alias 有问题，应该改成`alias pc='~/bin/proxychains4'`

**Comment by dowhilenet** [comment]
@MofeLee Sorry.改过来了，讲道理说，应该没有问题了呀。可是  还是不行。好奇怪

**Comment by mofelee** [comment]
https://github.com/rofl0r/proxychains-ng/issues/78 参考这个issue解决一下

**Comment by mofelee** [comment]
如果没有问题我就关掉这个issue了
