### ISSUE TITLE
推荐个我一直在用的翻墙服务商 Azure SSH

### ISSUE THREAD

**Issue by chemzqm** [MofeLee/how-to-fxxk-gfw#2]
网站：http://www.azuressh.asia/
优点是支持 ssh 和 vpn，比较省事，一个月查不到10块钱特别便宜。
缺点是速度一般不会很快，偶尔网站和服务也会挂掉。

**Comment by mofelee** [comment]
@chemzqm 首先感谢分享翻墙服务商
为了避免广告的嫌疑, 我希望更多的推荐 VPS 服务器, 而不是已经搭建好的服务
不过有空我会测试 azure 的网络是不是适合翻墙的~
