### ISSUE TITLE
hinet 设定

### ISSUE THREAD

**Issue by bigjimmy546** [MofeLee/how-to-fxxk-gfw#3]
大大好，
请问您有提到ｈｉｎｅｔ的服务器需要升级？可以说明一下吗？
我再ｈｉｎｅｔ上装了ｓｓ可以连上ｓｅｒｖｅｒ，但是无法外访。
但是用ｖｐｎ就没有问题。
谢谢

**Comment by mofelee** [comment]
如果要使用“锐速”这个东西加速访问的话需要升级内核到指定版本，一般情况不需要

外网无法访问可以先登录到主机中，假设端口号为1234，尝试
`telnet 127.0.0.1 1234`
或者
`telnet x.x.x.x(本机外网地址） 1234`
测试到底是服务没有开还是外网连接不上

如果测试都能连上，最好检查一下ss是不是最新版本的

如果是最新版本的，再回复下，我去测试测试。

**Comment by bigjimmy546** [comment]
telnet 全部连不上去 443，80，8000都不行
但是我同时有架设vpn，用vpn服务联外网就可以，没有调整过port
不知道要开哪些端口？
ss是2.8.2的版本，应该是最新的吧

**Comment by mofelee** [comment]
@bigjimmy546 请问你部署的ss端口是什么？是【登录到主机中】并尝试【telnet本机的端口】吗

**Comment by bigjimmy546** [comment]
我在 /etc/shadowsocks.json
的设定
     "server_port":80,
     "local_port":1080,
----------------------------------------
是【登录到主机中】并尝试【telnet本机的端口】

**Comment by mofelee** [comment]
使用 `ps aux | grep ss-server` 查看是否正确启动服务

![image](https://user-images.githubusercontent.com/5069410/29910170-6e925cc0-8e5b-11e7-80ab-5389b304356b.png)

**Comment by bigjimmy546** [comment]
我的ｏｕｔｐｕｔ是

root     20936  0.0  0.0  10448   688 pts/1    S+   19:49   0:00 grep
--color=auto *ss-server*

*這有在跑嗎？*

**Comment by mofelee** [comment]
@bigjimmy546 你没启动服务。。。

**Comment by mofelee** [comment]
没有疑问我就先关掉这个issue了，如果有疑问再提

**Comment by bigjimmy546** [comment]
抱歉，我看不太懂output，但是我用另外一台aliyun云的服务器，跑一样的command
结果是：root      9570  0.0  0.1  14224  1088 pts/0    S+   00:37   0:00 grep --color=auto ss-server
（看起来一样？）但是就是可以使用

**Comment by mofelee** [comment]
@bigjimmy546 请问你是用什么方法部署的ss？

**Comment by bigjimmy546** [comment]
我是依照这个方法
https://www.vpndada.com/how-to-setup-shadowsocks-server-on-amazon-ec2/

**Comment by mofelee** [comment]
试试`ps aux | grep ssserver`?

**Comment by bigjimmy546** [comment]
![screen shot 2017-09-04 at 1 36 38 am](https://user-images.githubusercontent.com/7572072/30005278-896f3d70-9111-11e7-9109-c96a11afa749.png)

**Comment by mofelee** [comment]
执行`cat /etc/shadowsocks.json`我看看具体配置是什么（记住删掉敏感信息，比如说密码什么的）

**Comment by bigjimmy546** [comment]
{
    "server":"xxxx",
     "server_port":80,
     "local_port":1080,
     "password":"xxxx",
     "timeout":600,
     "method":"chacha20"
}

**Comment by bigjimmy546** [comment]
我其他2台server的配置都是一样的。。晕
就hinet的不能用

**Comment by bigjimmy546** [comment]
hinet server 是直接放外网的ip，aws跟aliyun都是放内网ip

**Comment by mofelee** [comment]
嗯，我明天测试一下看怎么回事

**Comment by bigjimmy546** [comment]
感谢

**Comment by mofelee** [comment]
@bigjimmy546 测试过，那个教程在 HiNet 上的确有点问题，
建议使用[一键安装脚本安装](https://github.com/MofeLee/how-to-fxxk-gfw#部署)

```
wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks.sh
chmod +x shadowsocks.sh
./shadowsocks.sh 2>&1 | tee shadowsocks.log
```
![image](https://user-images.githubusercontent.com/5069410/30016378-72edd3f6-9187-11e7-9a0a-d6ba2b054f77.png)

测试过能正常安装

**Comment by bigjimmy546** [comment]
還是不行，telnet 自己ip，port 80也不行。。。
我再自己想辦法吧，謝謝大大

![img_4115](https://user-images.githubusercontent.com/7572072/30059412-a4b713bc-9271-11e7-87b5-aaad7e4786e9.JPG)

**Comment by mofelee** [comment]
@bigjimmy546 这是成功的标志。。。已经成功了。。

**Comment by mofelee** [comment]
![image](https://user-images.githubusercontent.com/5069410/30061545-552e0540-927a-11e7-96a6-51072acc2425.png)

Connected

**Comment by bigjimmy546** [comment]
哈，感谢大大的帮忙，测试之后发现，连不上fb、google、等网站。。。＠＃＠％
