### ISSUE TITLE
关于服务商的问题

### ISSUE THREAD

**Issue by eternalphane** [MofeLee/how-to-fxxk-gfw#4]
除了VPS之外，您是否尝试过使用Azure或Bluemix这样的云平台搭建代理呢？

**Comment by mofelee** [comment]
azure和bluemix没有试过，只试过aws，应该是因为成本比较高的原因没有继续用

**Comment by eternalphane** [comment]
azure的我看了下好像成本赶人...
bluemix感觉还好 今天刚搭完 准备用一个月试试水 到时候给您反馈～

**Comment by mofelee** [comment]
有点感动，哈哈~看啥时候有空我也整理整理文章。。之前写的有点草率

**Comment by eternalphane** [comment]
如果我没理解错的话大概是...免费？
![image](https://user-images.githubusercontent.com/11267872/32690329-f8fda376-c72f-11e7-9af8-abb01b0cbe02.png)
![image](https://user-images.githubusercontent.com/11267872/32690325-df02c2ee-c72f-11e7-819a-bc4cf08fdc0d.png)

**Comment by eternalphane** [comment]
唯一的问题是速度奇慢

**Comment by mofelee** [comment]
看了他的几个可用区，好像离中国都不近，而且要免费开双核四G的机器需要信用卡？好像有点麻烦。等速度快了再添加进列表好了😄😄

**Comment by mofelee** [comment]
免费的一般限制比较多，比如说宽带或者计算资源
并且使用容器服务搭建代理不方便开加速补丁(锐速或者bbr)
所以还是建议买个vps，比较省心，哈哈，不过还是谢谢你提供的信息

**Comment by mofelee** [comment]
没有问题就先关掉这个issue了
