### ISSUE TITLE
只有一台国外vps，如何实现ss转http代理，以便设备使用在线pac？

### ISSUE THREAD

**Issue by jakkpop** [MofeLee/how-to-fxxk-gfw#6]
RT，只有一台国外vps，如何实现ss转http代理，以便设备使用在线pac？
就是ios系统或win系统在网络输入一下在线pac就可以成功。
找了很多资料教程，都没有成功。

**Comment by mofelee** [comment]
ss转http代理只能在本机（使用ss客户端的机器）或路由器上使用..具体查查你的路由器支持不支持或者用polipo在本机转，然后在ios设置http代理填上本机的局域网ip地址

**Comment by mofelee** [comment]
如果没有问题我暂时close掉这个issue了
